import {
  Mountain,
  UtensilsCrossed,
  LandPlot,
  Film,
  Waves,
  Bike,
  Camera,
  Gamepad2,
  Dumbbell,
  Book,
  PersonStanding,
  Footprints,
  ShoppingBag,
  Paintbrush,
  Flower,
  Fish,
  Music,
  Tent,
  Microwave,
  CookingPot,
  HandHeart,
  Puzzle,
  Music4,
  MicVocal,
  Circle,
  Volleyball,
  Goal,
  Target,
  GlassWater,
  Mic2,
  Landmark,
  Drama,
  Shapes,
  Sparkles,
  Wine,
  Car,
  Binoculars,
  Sailboat,
  Snowflake,
  Store,
  Joystick,
  Bath,
  Flame,
  Squirrel,
} from "lucide-react";

export const ACTIVITIES = [
  { id: "hiking", label: "Hiking", icon: <Mountain className="size-6" /> },
  { id: "brunch", label: "Brunch", icon: <UtensilsCrossed className="size-6" /> },
  { id: "golf", label: "Golf", icon: <LandPlot className="size-6" /> },
  { id: "movie", label: "Movie", icon: <Film className="size-6" /> },
  { id: "swimming", label: "Swimming", icon: <Waves className="size-6" /> },
  { id: "cycling", label: "Cycling", icon: <Bike className="size-6" /> },
  { id: "picnic", label: "Picnic", icon: <Tent className="size-6" /> }, // Tent as placeholder
  { id: "gaming", label: "Gaming", icon: <Gamepad2 className="size-6" /> },
  { id: "yoga", label: "Yoga", icon: <PersonStanding className="size-6" /> }, // you may import PersonStanding
  { id: "reading", label: "Reading", icon: <Book className="size-6" /> },
  { id: "running", label: "Running", icon: <Footprints className="size-6" /> },
  { id: "shopping", label: "Shopping", icon: <ShoppingBag className="size-6" /> },
  { id: "painting", label: "Painting", icon: <Paintbrush className="size-6" /> },
  { id: "gardening", label: "Gardening", icon: <Flower className="size-6" /> },
  { id: "fishing", label: "Fishing", icon: <Fish className="size-6" /> },
  { id: "dancing", label: "Dancing", icon: <Music className="size-6" /> },
  { id: "photography", label: "Photography", icon: <Camera className="size-6" /> },
  { id: "camping", label: "Camping", icon: <Tent className="size-6" /> },
  { id: "baking", label: "Baking", icon: <Microwave className="size-6" /> },
  { id: "cooking", label: "Cooking", icon: <CookingPot className="size-6" /> },
  { id: "volunteering", label: "Volunteering", icon: <HandHeart className="size-6" /> },
  { id: "board_games", label: "Board Games", icon: <Puzzle className="size-6" /> },
  { id: "music", label: "Listening to Music", icon: <Music4 className="size-6" /> },
  { id: "concert", label: "Concert", icon: <MicVocal className="size-6" /> },
  { id: "bowling", label: "Bowling", icon: <Circle className="size-6" /> },
  { id: "tennis", label: "Tennis", icon: <Volleyball className="size-6" /> }, // Volleyball looks close
  { id: "badminton", label: "Badminton", icon: <Volleyball className="size-6" /> },
  { id: "basketball", label: "Basketball", icon: <Circle className="size-6" /> }, // Generic ball
  { id: "soccer", label: "Soccer", icon: <Goal className="size-6" /> },
  { id: "cricket", label: "Cricket", icon: <Target className="size-6" /> }, // Target as placeholder
  { id: "pool", label: "Pool", icon: <GlassWater className="size-6" /> },
  { id: "karaoke", label: "Karaoke", icon: <Mic2 className="size-6" /> },
  { id: "museum", label: "Museum Visit", icon: <Landmark className="size-6" /> },
  { id: "theatre", label: "Theatre Play", icon: <Drama className="size-6" /> },
  { id: "pottery", label: "Pottery", icon: <Shapes className="size-6" /> },
  { id: "meditation", label: "Meditation", icon: <Sparkles className="size-6" /> },
  { id: "wine-tasting", label: "Wine Tasting", icon: <Wine className="size-6" /> },
  { id: "road_trip", label: "Road Trip", icon: <Car className="size-6" /> },
  { id: "sightseeing", label: "Sightseeing", icon: <Binoculars className="size-6" /> },
  { id: "surfing", label: "Surfing", icon: <Waves className="size-6" /> },
  { id: "kayaking", label: "Kayaking", icon: <Sailboat className="size-6" /> },
  { id: "skiing", label: "Skiing", icon: <Snowflake className="size-6" /> },
  { id: "snowboarding", label: "Snowboarding", icon: <Snowflake className="size-6" /> },
  { id: "skating", label: "Skating", icon: <Circle className="size-6" /> }, // Generic
  { id: "shopping-mall", label: "Mall Visit", icon: <Store className="size-6" /> },
  { id: "arcade", label: "Arcade", icon: <Joystick className="size-6" /> },
  { id: "fitness", label: "Gym Workout", icon: <Dumbbell className="size-6" /> },
  { id: "spa", label: "Spa Day", icon: <Bath className="size-6" /> },
  { id: "barbecue", label: "Barbecue", icon: <Flame className="size-6" /> },
  { id: "zoo", label: "Zoo Visit", icon: <Squirrel className="size-6" /> },
  { id: "aquarium", label: "Aquarium Visit", icon: <Fish className="size-6" /> },
];
