// data/activitiesData.js
export const ACTIVITIES = [
  { id: "hiking", label: "Hiking" },
  { id: "brunch", label: "Brunch" },
  { id: "golf", label: "Golf" },
  { id: "movie", label: "Movie" },
  { id: "swimming", label: "Swimming" },
  { id: "cycling", label: "Cycling" },
  { id: "picnic", label: "Picnic" },
  { id: "gaming", label: "Gaming" },
  { id: "yoga", label: "Yoga" },
  { id: "reading", label: "Reading" },
  { id: "running", label: "Running" },
  { id: "shopping", label: "Shopping" },
  { id: "painting", label: "Painting" },
  { id: "gardening", label: "Gardening" },
  { id: "fishing", label: "Fishing" },
  { id: "dancing", label: "Dancing" },
  { id: "photography", label: "Photography" },
  { id: "camping", label: "Camping" },
  { id: "baking", label: "Baking" },
  { id: "cooking", label: "Cooking" },
  { id: "volunteering", label: "Volunteering" },
  { id: "board_games", label: "Board Games" },
  { id: "music", label: "Listening to Music" },
  { id: "concert", label: "Concert" },
  { id: "bowling", label: "Bowling" },
  { id: "tennis", label: "Tennis" },
  { id: "badminton", label: "Badminton" },
  { id: "basketball", label: "Basketball" },
  { id: "soccer", label: "Soccer" },
  { id: "cricket", label: "Cricket" },
  { id: "pool", label: "Pool" },
  { id: "karaoke", label: "Karaoke" },
  { id: "museum", label: "Museum Visit" },
  { id: "theatre", label: "Theatre Play" },
  { id: "pottery", label: "Pottery" },
  { id: "meditation", label: "Meditation" },
  { id: "wine-tasting", label: "Wine Tasting" },
  { id: "road_trip", label: "Road Trip" },
  { id: "sightseeing", label: "Sightseeing" },
  { id: "surfing", label: "Surfing" },
  { id: "kayaking", label: "Kayaking" },
  { id: "skiing", label: "Skiing" },
  { id: "snowboarding", label: "Snowboarding" },
  { id: "skating", label: "Skating" },
  { id: "shopping-mall", label: "Mall Visit" },
  { id: "arcade", label: "Arcade" },
  { id: "fitness", label: "Gym Workout" },
  { id: "spa", label: "Spa Day" },
  { id: "barbecue", label: "Barbecue" },
  { id: "zoo", label: "Zoo Visit" },
  { id: "aquarium", label: "Aquarium Visit" },
];
